name: ' Build and Publish'

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target rtl433_to_mqtt \
          --image rtl433_to_mqtt \
          --docker-hub reichley
